swagger: "2.0"
info:
  title: Graph Visualizer
  description: API description in Markdown.
  version: 0.0.1
host: localhost:80
basePath: /myapp/public/index
schemes:
  - http
paths:
  /users:
    get:
      summary: Returns a list of users.
      description: Optional extended description in Markdown.
      produces:
        - application/json
      responses:
        200:
          description: OK
